# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='role',
            field=models.CharField(choices=[('GE', '\u0411\u0430\u0437\u043e\u0432\u0430\u044f'), ('NW', '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'), ('RC', '\u0420\u0435\u043a\u043e\u043c\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u0438'), ('PJ', '\u041f\u0440\u043e\u0435\u043a\u0442\u044b'), ('PR', '\u041f\u0440\u043e\u0444\u0438\u043b\u044c'), ('PC', '\u041f\u0440\u043e\u0444\u0438\u043b\u044c - \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'), ('MN', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f'), ('CT', '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b')], default='GE', max_length=2, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.Page', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
