# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160609_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_url', models.CharField(max_length=200, verbose_name='Facebook')),
                ('insta_url', models.CharField(max_length=200, verbose_name='Instagramm')),
                ('vk_url', models.CharField(max_length=200, verbose_name='Vkontakte')),
                ('youtube_url', models.CharField(max_length=200, verbose_name='Youtube')),
                ('twitter_url', models.CharField(max_length=200, verbose_name='Twitter')),
                ('phone', models.CharField(max_length=200, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('address', models.CharField(max_length=200, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('mail', models.CharField(max_length=200, verbose_name='\u041f\u043e\u0447\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438',
                'verbose_name_plural': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438',
            },
        ),
    ]
