# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0435\u043a\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='WorkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('use_video', models.BooleanField(default=False, verbose_name='\u0412\u0438\u0434\u0435\u043e\u0431\u044d\u043a\u0433\u0440\u0430\u0443\u043d\u0434?')),
                ('image', sorl.thumbnail.fields.ImageField(null=True, upload_to='news/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('video', embed_video.fields.EmbedVideoField(null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 youtube')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='works.Work', verbose_name='\u041f\u0440\u043e\u0435\u043a\u0442')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u043e\u0441\u0442\u0438',
            },
        ),
    ]
