# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 19:38
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpart',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='works/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='workpart',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 youtube'),
        ),
    ]
