# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20160614_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='published',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e?'),
        ),
    ]
