# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_work_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0430\u0432\u043d\u0438\u0435'),
        ),
    ]
